import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Eric Zhu</title>
        <meta name="viewport" content="width=device-width"/>
        {/*<meta name="description" content="Generated by create next app" />*/}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="font-serif text-6xl m-5 leading-tight">
          Eric Zhu
        </h1>

        <div className={styles.grid}>
          <Link href="/contact">Contact</Link>
        </div>
      </main>
    </div>
  )
}

export default Home
